#! /bin/sh

MON1=DisplayPort-0
MON2=DisplayPort-1

killall sxhkd

bspc monitor $MON1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor $MON2 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         5
bspc config window_gap          0

bspc config focused_border_color "#50dfa0"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus follows mouse
bspc config focus_follows_pointer true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

~/.config/dwm/random-wallpaper.sh

sxhkd &
/vol/config/polybar/launch.sh
dunst &
numlockx on

